### ISSUE TITLE
Llamada incorrecta, el API Key es obligatorio

### ISSUE THREAD

**Issue by remo285** [GrosfeldEzekiel/mobbex-node#13]
Estaba testeando para crear un checkout, pero al momento de hacer el request hacia mobbex me devuelve esto
`{
  result: false,
  code: 'UCAKR',
  error: 'Llamada incorrecta, el API Key es obligatorio'
}
`
tengo el api key configurado como dice en la documentacion 
`mobbex.configurations.configure({
    apiKey: 'zJ8LFTBX6Ba8D611e9io13fDZAwj0QmKO1Hn1yIj-KEY',
    accessToken: 'd31f0721-2f85-44e7-bcc6-15e19d1a53cc'
})`
es la apiKey y el access token de prueba que provee mobbex
el objeto del checkout se ve asi
`const checkout = {
        total: link.monto,
        currency: "ARS",
        reference: `${link._id}`,
        description: `Venta de ${link.nombrePerfume}`,
        items: [
            {
                quantity: 1,
                description: `${link.nombrePerfume}`,
                total: link.monto,
            }],
        options: {
            domain: "http://localhost:4000",
        },
        return_url: "http://localhost:4000/checkout/completed",
        //webhook: "https://mobbex.com/sale/webhook?user=1234"
    }`
talvez sea un problema de la url que estoy dandonle?, ya que es la url de mi sistema local.
por si es necesario saber, mi sistema usa node.js con express.

**Comment by ezegros** [comment]
Hola, el error ocurre cuando el API key es incorrecto. Quizá el "-KEY" al final de `'zJ8LFTBX6Ba8D611e9io13fDZAwj0QmKO1Hn1yIj-KEY'` no va o es incorrecto.

**Comment by remo285** [comment]
Si, ese era el problema, no me habia fijado en eso, gracias por la ayuda.
pd: buen paquete!, hace la integracion de mobbex bastante mas simple en el sistema.
